<?php

return [

    'permission_slugs' => [
        'view-users',
        'create-users',
        'update-users',
        'delete-users',
        'view-permissions',
        'create-permissions',
        'update-permissions',
        'delete-permissions',
        'view-roles',
        'create-roles',
        'update-roles',
        'delete-roles',
        'role-permissions',
        'user-permissions',
        'view-books',
        'create-books',
        'update-books',
        'delete-books',
        'view-charges',
        'create-charges',
        'update-charges',
        'delete-charges',
        'view-products',
        'add-product',
        'view-applicants',
        'add-applicant',
        'update-applicants',
        'sync-applicant-products',
        'update-product-status',
        'update-applicant-status',
        'get-credit-limit',
        'assign-credit-limit',
        'initiate-transaction',
        'view-transactions',
        'assign-financing-policy',
        'loan-details',
        'pay-installment',
        'view-repayments',
        'change-password',
        'refresh-ofac-nacta',
        'refresh-credit-score',
        'refresh-shipper-info',
        'refresh-shipper-kyc',
        'refresh-shipper-pricing',
        'export-transactions',
        'export-repayments',
        'view-dashboard',
        'view-reports'
    ],

    // 'role_slugs' => [
    //     'finance-manager' => [
    //         'view-users',
    //         'create-users',
    //         'update-users',
    //         'delete-users',
    //         'view-permissions',
    //         'create-permissions',
    //         'update-permissions',
    //         'delete-permissions',
    //         'view-roles',
    //         'create-roles',
    //         'update-roles',
    //         'delete-roles',
    //     ]
    // ],

];
